version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  chatbot:
    build: .
    container_name: synapsis-chatbot
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_MODEL=llama3.2:3b
      - CHATBOT_DB=/app/chatbot.db
    volumes:
      - ./chatbot.db:/app/chatbot.db
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data:
